### ISSUE TITLE
After upgrade to v4.2, I got JSON for model 'pan_logs' is invalid error message

### ISSUE THREAD

**Issue by rolandcheung** [PaloAltoNetworks-BD/SplunkforPaloAltoNetworks#10]
Hi,

After upgrade to v4.2, I got
Error in model "pan_logs" : Error in 'DataModelEvaluator': JSON for model 'pan_logs' is invalid.
error message.

Currently, I am using
PanOS 5.0.x
Splunk 6.1.1

I check the firewall log forwarding setting which only provide syslog in current PanOS 5.0.x, is it the root  cause of problem or I have missed any configuration ?

Thanks

**Comment by btorresgil** [comment]
Haven't been able to reproduce this issue.  Most likely the json for the datamodel was modified or corrupted somehow on your system.

Closing this issue for now, but re-open if this is still a problem.
