### ISSUE TITLE
WildFire Cloud API not working

### ISSUE THREAD

**Issue by lucperreau** [PaloAltoNetworks-BD/SplunkforPaloAltoNetworks#13]
Even if the API key is applied correctly, the cloud logs still do not appear in Splunk.

**Comment by btorresgil** [comment]
The Wildfire API key is used by Splunk to get the full Wildfire report for an incident reported by the firewall.  But if Splunk isn't getting wildfire logs from the firewall, it will never try to get a report using the API key.  Make sure you have malicious Wildfire syslogs being sent from a firewall to Splunk.  Only in this case will the API key be used.

You can check for malicious Wildfire logs in Splunk using this search:

    `pan_wildfire` category="malicious"

Or on the firewall under the Monitor tab -> Wildfire Submissions.

To configure the firewall to send Wildfire logs to Splunk, use the documentation available here:
  http://pansplunk.readthedocs.org/en/latest/advanced.html#wildfire

Closing this issue for now as other customer are not reporting the same issue.  If you are still experiencing an issue getting Wildfire reports using the API, please re-open or work with me at http://answers.splunk.com.  Thanks!

**Comment by lucperreau** [comment]
Thanks Brian.
