### ISSUE TITLE
Data model  acceleration is very slow

### ISSUE THREAD

**Issue by hkguy80** [PaloAltoNetworks-BD/SplunkforPaloAltoNetworks#7]
I have updated the Splunk to 6.1 and using the latest Palo Alto App(4.1.1).  Although the new App no longer have the unlimited TSIDX issue, it is take very long time to generated the data model.  

I have already applied the solution from the following link.
http://answers.splunk.com/answers/138840/only-the-overview-dashboard-has-data-pan-app-v4-1-1-splunk-v6-1-1.html
But it still took more than 1 month to accelerated 11% of data model and the total size is 420G. 

Regards,
Kevin

**Comment by btorresgil** [comment]
There have been several optimizations to the app's datamodel that make it more efficient in summarization performance and disk space usage.  I've sent our revised datamodel to the datamodel product managers at Splunk and worked with them to ensure the datamodel in the app is as efficient as possible.

The datamodel in the latest version (currently 5.0.1) is the result of that work, so upgrading to the latest app version will give you the benefits.

If after upgrading you are still experiencing performance issues, this is usually something that needs troubleshooting with Splunk support. The most common issue is not enough hardware resources to handle the quantity of logs being accelerated by the datamodel.  Which means the most common fixes are to add more compute resources or reduce the number of logs by being more selective about what is logged to Splunk.  However, there can be other issues or optimizations, and Splunk support can help determine the most likely cause of any performance issues.

Closing this issue now based on the optimizations made to the datamodel in the latest app versions.
